language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run build
on:
  branch: master
notifications:
  webhooks:
  urls:
    - http://megp.soc.srcf.net/deploy.php?sat=PzkRaebuBzwueVX8YHCaypUC
  on_success: always # default: always
  on_failure: never # default: always
  on_start: never   # default: never
  on_cancel: never # default: always
  on_error: never # default: always
